// Lista de preguntas (al menos 50) en español
// Cada pregunta: { question: '', choices: [...], correctIndex: n }
window.QUESTIONS = [
  { question: '¿Quién dirigió la película "Titanic" (1997)?', choices: ['James Cameron','Steven Spielberg','Martin Scorsese','Ridley Scott'], correctIndex: 0 },
  { question: '¿En qué año se estrenó "El Padrino"?', choices: ['1972','1969','1974','1980'], correctIndex: 0 },
  { question: '¿Cuál es la película más taquillera de todos los tiempos (sin ajustar inflación) hasta 2020?', choices: ['Avatar','Avengers: Endgame','Titanic','Star Wars: The Force Awakens'], correctIndex: 0 },
  { question: '¿Qué actor interpretó a Jack Dawson en "Titanic"?', choices: ['Brad Pitt','Leonardo DiCaprio','Tom Cruise','Matt Damon'], correctIndex: 1 },
  { question: '¿Cuál de estas películas ganó el Óscar a Mejor Película en 1994?', choices: ['Pulp Fiction','Forrest Gump','The Shawshank Redemption','Four Weddings and a Funeral'], correctIndex: 1 },
  { question: '¿Qué película presenta a un personaje llamado "Darth Vader"?', choices: ['Star Trek','Star Wars','Battlestar Galactica','Guardians of the Galaxy'], correctIndex: 1 },
  { question: '¿Quién dirigió "Pulp Fiction"?', choices: ['Quentin Tarantino','Guy Ritchie','David Fincher','Wes Anderson'], correctIndex: 0 },
  { question: '¿Cuál es la nacionalidad del director Guillermo del Toro?', choices: ['Español','Mexicano','Argentino','Colombiano'], correctIndex: 1 },
  { question: '¿Quién interpretó al Joker en "The Dark Knight" (2008)?', choices: ['Heath Ledger','Joaquin Phoenix','Jack Nicholson','Jared Leto'], correctIndex: 0 },
  { question: '¿Qué película incluye la canción "My Heart Will Go On"?', choices: ['The Bodyguard','Titanic','Romeo + Juliet','A Star Is Born'], correctIndex: 1 },
  { question: '¿En qué ciudad transcurre principalmente "Lost in Translation"?', choices: ['Seúl','Tokio','Pekín','Shanghai'], correctIndex: 1 },
  { question: '¿Qué director es conocido por la trilogía de "El Señor de los Anillos"?', choices: ['Peter Jackson','Christopher Nolan','Peter Weir','Terry Gilliam'], correctIndex: 0 },
  { question: '¿Cuál es la profesión del protagonista en "The Matrix" (Neo)?', choices: ['Programador','Carpintero','Abogado','Dentista'], correctIndex: 0 },
  { question: '¿En qué película aparece el personaje Hannibal Lecter?', choices: ['Silence of the Lambs','Se7en','The Shining','Psycho'], correctIndex: 0 },
  { question: '¿Quién dirigió "Inception"?', choices: ['Christopher Nolan','M. Night Shyamalan','Denis Villeneuve','James Wan'], correctIndex: 0 },
  { question: '¿Qué película de Pixar cuenta la historia de un ratón aspirante a chef?', choices: ['Ratatouille','Wall·E','Up','Toy Story'], correctIndex: 0 },
  { question: '¿Qué actor protagoniza la saga "Mission: Impossible" (Ethan Hunt)?', choices: ['Tom Cruise','Bradley Cooper','Chris Hemsworth','Mark Wahlberg'], correctIndex: 0 },
  { question: '¿Cómo se llama el joven mago protagonista en la saga de "Harry Potter"?', choices: ['Harry Potter','Neville Longbottom','Ron Weasley','Draco Malfoy'], correctIndex: 0 },
  { question: '¿Cuál de estas películas fue dirigida por Stanley Kubrick?', choices: ['2001: A Space Odyssey','Blade Runner','Alien','Close Encounters'], correctIndex: 0 },
  { question: '¿Qué película cuenta la historia de Andy Dufresne?', choices: ['The Green Mile','The Shawshank Redemption','A Time to Kill','The Mist'], correctIndex: 1 },
  { question: '¿Qué película de 1980 es famosa por la frase "I am your father"?', choices: ['The Empire Strikes Back','Return of the Jedi','A New Hope','Rogue One'], correctIndex: 0 },
  { question: '¿Quién interpretó a Indiana Jones?', choices: ['Harrison Ford','Sean Connery','Mel Gibson','Kurt Russell'], correctIndex: 0 },
  { question: '¿Qué cineasta es conocido por usar colores vivos y simetría, dirigió "The Grand Budapest Hotel"?', choices: ['Wes Anderson','Paul Thomas Anderson','Spike Jonze','Tim Burton'], correctIndex: 0 },
  { question: '¿Cuál es el nombre del grupo de ladrones en "Ocean’s Eleven" original (2001)?', choices: ['Danny Ocean y su equipo','The Expendables','The Usual Suspects','The Gentlemen'], correctIndex: 0 },
  { question: '¿Qué película ganó el Óscar a Mejor Película en 2010?', choices: ['The Hurt Locker','Avatar','Inception','The King’s Speech'], correctIndex: 0 },
  { question: '¿Cuál es la película de 1999 que popularizó la frase "There is no spoon"?', choices: ['The Matrix','Fight Club','The Sixth Sense','American Beauty'], correctIndex: 0 },
  { question: '¿Qué director hizo "Schindler’s List"?', choices: ['Steven Spielberg','Roman Polanski','Ang Lee','Clint Eastwood'], correctIndex: 0 },
  { question: '¿Qué película animada es conocida por la canción "Let It Go"?', choices: ['Frozen','Moana','Tangled','Brave'], correctIndex: 0 },
  { question: '¿Qué actriz protagoniza "La La Land" junto a Ryan Gosling?', choices: ['Emma Stone','Natalie Portman','Anne Hathaway','Carey Mulligan'], correctIndex: 0 },
  { question: '¿En qué película aparece el personaje Tyler Durden?', choices: ['Fight Club','Se7en','American Psycho','Oldboy'], correctIndex: 0 },
  { question: '¿Cuál de estas películas es de Hayao Miyazaki?', choices: ['Spirited Away','Akira','Ghost in the Shell','Paprika'], correctIndex: 0 },
  { question: '¿Qué película de Tarantino contiene la escena de baile en la que participan Uma Thurman y John Travolta?', choices: ['Pulp Fiction','Kill Bill','Django Unchained','Jackie Brown'], correctIndex: 0 },
  { question: '¿Quién compuso la banda sonora de "Interstellar"?', choices: ['Hans Zimmer','John Williams','Alexandre Desplat','Howard Shore'], correctIndex: 0 },
  { question: '¿Qué película ganó el Óscar a Mejor Película en 2003?', choices: ['The Lord of the Rings: The Return of the King','Chicago','A Beautiful Mind','Gladiator'], correctIndex: 0 },
  { question: '¿En qué película de animación aparece el personaje Woody?', choices: ['Toy Story','Cars','Monsters, Inc.','Finding Nemo'], correctIndex: 0 },
  { question: '¿Qué película protagoniza Marlon Brando como Vito Corleone?', choices: ['The Godfather','On the Waterfront','Apocalypse Now','Streetcar Named Desire'], correctIndex: 0 },
  { question: '¿Qué película presenta la playa de Omaha en su trama de guerra?', choices: ['Saving Private Ryan','Platoon','Full Metal Jacket','Apocalypse Now'], correctIndex: 0 },
  { question: '¿Qué director realizó "Blade Runner 2049"?', choices: ['Denis Villeneuve','Ridley Scott','Christopher Nolan','James Cameron'], correctIndex: 0 },
  { question: '¿Cuál es la película sobre un pianista en un barco que se basa en una novela de 1997?', choices: ['The Legend of 1900','The Piano','Amadeus','The Red Violin'], correctIndex: 0 },
  { question: '¿Qué película de 1994 protagoniza Tim Robbins y Morgan Freeman?', choices: ['The Shawshank Redemption','Pulp Fiction','Forrest Gump','Speed'], correctIndex: 0 },
  { question: '¿Qué película de ciencia ficción fue dirigida por Denis Villeneuve y basada en una novela de Frank Herbert?', choices: ['Dune','Arrival','Blade Runner 2049','The Martian'], correctIndex: 0 },
  { question: '¿Qué película de comedia romántica protagonizó Hugh Grant en los 90s?', choices: ['Four Weddings and a Funeral','Notting Hill','Bridget Jones’s Diary','Love Actually'], correctIndex: 0 },
  { question: '¿Qué actriz interpreta a Ripley en "Alien"?', choices: ['Sigourney Weaver','Linda Hamilton','Jodie Foster','Carrie Fisher'], correctIndex: 0 },
  { question: '¿Qué director es famoso por "Jaws"?', choices: ['Steven Spielberg','Alfred Hitchcock','John Carpenter','Martin Scorsese'], correctIndex: 0 },
  { question: '¿En qué película aparece la línea "Here’s looking at you, kid"?', choices: ['Casablanca','Gone with the Wind','Citizen Kane','Singin’ in the Rain'], correctIndex: 0 },
  { question: '¿Qué película de 2019 ganó el Óscar a Mejor Película?', choices: ['Parasite','1917','Joker','Once Upon a Time in Hollywood'], correctIndex: 0 },
  { question: '¿Qué película protagoniza Natalie Portman y trata sobre una bailarina?', choices: ['Black Swan','Cisne Negro','The Wrestler','Whiplash'], correctIndex: 0 },
  { question: '¿Qué película cuenta la historia del boxeador Rocky Balboa?', choices: ['Rocky','Raging Bull','Creed','Million Dollar Baby'], correctIndex: 0 },
  { question: '¿Qué película presenta a un robot llamado WALL·E?', choices: ['WALL·E','Big Hero 6','Robots','The Iron Giant'], correctIndex: 0 },
  { question: '¿Qué película cuenta la historia de una isla con dinosaurios creada por clonación?', choices: ['Jurassic Park','King Kong','Godzilla','The Lost World'], correctIndex: 0 },
  { question: '¿Cuál de estas películas es de Alfred Hitchcock?', choices: ['Psycho','Vertigo','Rear Window','Todas las anteriores'], correctIndex: 3 },
  { question: '¿Qué actor protagoniza "Gladiator" como Máximo?', choices: ['Russell Crowe','Joaquin Phoenix','Denzel Washington','Tom Hanks'], correctIndex: 0 },
  { question: '¿Qué película musical protagoniza Judy Garland y trata de una niña que canta sobre un país de fantasía?', choices: ['The Wizard of Oz','Singin’ in the Rain','The Sound of Music','Mary Poppins'], correctIndex: 0 },
  { question: '¿Qué película tiene como tema central la sobrevivencia en el espacio con un astronauta llamado Mark Watney?', choices: ['The Martian','Gravity','Interstellar','Apollo 13'], correctIndex: 0 },
  { question: '¿Qué director ganó el Óscar por "The Hurt Locker"?', choices: ['Kathryn Bigelow','Kathryn Bigelow','Ben Affleck','Clint Eastwood'], correctIndex: 0 }
];
